-- HAND-EDITED MIGRATION
-- This file was auto-generated by drizzle-kit then edited to:
--   1. Make legacy table/column/FK additions idempotent (because the original
--      netlify/functions/migrate.ts created passage_versions, replacements,
--      speakers, and the speaker/unversioned_rendering columns directly,
--      without a corresponding Drizzle migration — they may or may not exist
--      in the target DB).
--   2. Defer the projects.team_id NOT NULL constraint until after backfilling
--      every existing project into a new 'Default' team that contains every
--      existing user (via users.team_ids).
-- If drizzle-kit regenerates this file, the hand edits will be lost.

CREATE TABLE IF NOT EXISTS "passage_versions" (
	"id" serial PRIMARY KEY NOT NULL,
	"passage_id" integer NOT NULL,
	"audio_key" varchar(255) NOT NULL,
	"render_source" varchar(255),
	"note" varchar(255) DEFAULT '' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "replacements" (
	"id" serial PRIMARY KEY NOT NULL,
	"passage_id" integer NOT NULL,
	"title" varchar(255) NOT NULL,
	"note" varchar(255) DEFAULT '' NOT NULL,
	"name" varchar(255) DEFAULT '' NOT NULL,
	"selection_start" double precision NOT NULL,
	"selection_end" double precision NOT NULL,
	"audio_key" varchar(255),
	"original" boolean DEFAULT true NOT NULL,
	"version_id" integer,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "speakers" (
	"name" varchar(255) PRIMARY KEY NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "teams" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "password_hash" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "passages" ADD COLUMN IF NOT EXISTS "unversioned_rendering" varchar(255);--> statement-breakpoint
ALTER TABLE "passages" ADD COLUMN IF NOT EXISTS "speaker" varchar(255);--> statement-breakpoint
ALTER TABLE "projects" ADD COLUMN "team_id" integer;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "team_ids" integer[] DEFAULT '{}'::int[] NOT NULL;--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "passage_versions" ADD CONSTRAINT "passage_versions_passage_id_passages_id_fk" FOREIGN KEY ("passage_id") REFERENCES "public"."passages"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "replacements" ADD CONSTRAINT "replacements_passage_id_passages_id_fk" FOREIGN KEY ("passage_id") REFERENCES "public"."passages"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "replacements" ADD CONSTRAINT "replacements_version_id_passage_versions_id_fk" FOREIGN KEY ("version_id") REFERENCES "public"."passage_versions"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;--> statement-breakpoint
ALTER TABLE "projects" ADD CONSTRAINT "projects_team_id_teams_id_fk" FOREIGN KEY ("team_id") REFERENCES "public"."teams"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
-- Backfill: create a 'Default' team, add every existing user to it,
-- and assign every existing project to it. Idempotent (won't double-create
-- the Default team if rerun).
INSERT INTO "teams" ("name") SELECT 'Default' WHERE NOT EXISTS (SELECT 1 FROM "teams" WHERE "name" = 'Default');--> statement-breakpoint
UPDATE "users" SET "team_ids" = ARRAY[(SELECT id FROM "teams" WHERE name = 'Default')] WHERE "team_ids" = '{}'::int[];--> statement-breakpoint
UPDATE "projects" SET "team_id" = (SELECT id FROM "teams" WHERE name = 'Default') WHERE "team_id" IS NULL;--> statement-breakpoint
ALTER TABLE "projects" ALTER COLUMN "team_id" SET NOT NULL;
